defaults:
  - dynamics: bicopter
  - task: pc
  - algo: TBPTT 
  - _self_

cm: srt      # Default control mode (suported: srt,ctbr,lv)
device: "cuda"

dt: 0.01
epochs: ${env.epochs}
steps: ${env.steps}
# horizon: 50
num_envs: ${env.num_envs}