hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - cm=ctbr,lv
  job:
    name: train
    chdir: null
    override_dirname: cm=ctbr,lv
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/adame/diffRL
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/adame/diffRL/cfg
      schema: file
      provider: main
    - path: hydra_plugins.hydra_colorlog.conf
      schema: pkg
      provider: hydra-colorlog
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      task: trck
      dynamics: bicopter
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
dynamics:
  name: simple_2D_drone
  cm: ctbr
  nf: 0.2
  sf:
    nominal: 0.5
    randomize: true
    min: 0.0
    max: 1.0
  arm_l:
    nominal: 0.2
    randomize: true
    min: 0.1
    max: 0.3
  mass:
    nominal: 1.0
    randomize: true
    min: 0.5
    max: 1.5
  J:
    nominal: 0.01
    randomize: true
    min: 0.005
    max: 0.015
  C_D:
    x:
      nominal: 0.1
      randomize: true
      min: 0.05
      max: 0.15
    'y':
      nominal: 0.1
      randomize: true
      min: 0.05
      max: 0.15
  c_tf:
    nominal: 0.012
    randomize: true
    min: 0.005
    max: 0.015
  km:
    up:
      nominal: 0.033
      randomize: true
      min: 0.01
      max: 0.05
    down:
      nominal: 0.044
      randomize: true
      min: 0.02
      max: 0.06
  thrust_map:
    k1:
      nominal: 2.0e-07
      randomize: true
      min: 1.0e-07
      max: 3.0e-07
    k2: null
    k3: null
  Ti_min: 0.0
  Ti_max: 15.0
  motor_acc_min: -80000.0
  motor_acc_max: 50000.0
  motor_speed_min: 150.0
  motor_speed_max: 8400.0
  omega_max: null
  g: 9.81
  rho: 1.225
task:
  name: target_tracking
  abbr: trck
cm: ctbr
dt: 0.01
steps: 300
horizon: 20
epochs: 100
num_envs: 1024
